<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="SmokeTestScenario" duration-ms="83" started-at="2019-01-24T12:09:03Z" finished-at="2019-01-24T12:09:03Z">
    <groups>
    </groups>
    <test name="Sprint1" duration-ms="83" started-at="2019-01-24T12:09:03Z" finished-at="2019-01-24T12:09:03Z">
      <class name="testNGClasses.TestCase3">
        <test-method status="FAIL" signature="testWordpress()[pri:0, instance:testNGClasses.TestCase3@7ac7a4e4]" name="testWordpress" duration-ms="17" started-at="2019-01-24T12:09:03Z" finished-at="2019-01-24T12:09:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testNGClasses.TestCase3.testWordpress(TestCase3.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWordpress -->
      </class> <!-- testNGClasses.TestCase3 -->
      <class name="testNGClasses.TestCase2">
        <test-method status="PASS" signature="testTwitter()[pri:0, instance:testNGClasses.TestCase2@5f375618]" name="testTwitter" duration-ms="2" started-at="2019-01-24T12:09:03Z" finished-at="2019-01-24T12:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwitter -->
      </class> <!-- testNGClasses.TestCase2 -->
      <class name="testNGClasses.TestCase1">
        <test-method status="PASS" signature="testFB()[pri:0, instance:testNGClasses.TestCase1@1810399e]" name="testFB" duration-ms="3" started-at="2019-01-24T12:09:03Z" finished-at="2019-01-24T12:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFB -->
      </class> <!-- testNGClasses.TestCase1 -->
    </test> <!-- Sprint1 -->
  </suite> <!-- SmokeTestScenario -->
</testng-results>
